Update Requirements.yml

diff --git a/.github/workflows/Requirements.yml b/.github/workflows/Requirements.yml
--- a/.github/workflows/Requirements.yml
+++ b/.github/workflows/Requirements.yml
@@ -9,6 +9,18 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v2
 
+    - name: Validar secret
+      env:
+        TITLE: ${{ secret.GITHUB }}
+        run: |
+          if [[ "$TITLE" =~ ^crnic ]]; then
+          echo "Token Valido"
+          exit 0
+          else
+          echo "Token INvalido"
+          exit 1
+          fi  
+
     - name: Ejecutar flujo de trabajo reusable
       uses: devops-dabu/reusable/.github/workflows/reusable-lab.yml@main
       with:
